---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: cavcrosby/setup-pyenv@v1.0.0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - id: setup-makefiles
        uses: cavcrosby/setup-makefiles@v1.0.0

      - name: Initialize project
        run: python -m pip install "setuptools>=61.0.0" "."

      - name: Run tests
        run: make --include-dir "${{ steps.setup-makefiles.outputs.CAVCROSBY_MAKEFILES_PATH }}" test  # yamllint disable-line rule:line-length
