---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cavcrosby/setup-pyenv@v1.0.0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - id: setup-makefiles
        uses: cavcrosby/setup-makefiles@v1.0.0

      - name: Initialize project
        run: python -m pip install "."

      - name: Run tests
        run: make --include-dir "${{ steps.setup-makefiles.outputs.CAVCROSBY_MAKEFILES_PATH }}" test  # yamllint disable-line rule:line-length
