---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Initialize project
        run: make setup

      - name: Run unit tests
        run: make test
